### ISSUE TITLE
finalize game engine choice (+programming language)

### ISSUE THREAD

**Issue by katiepo456** [CSI-280-Fish-Game/Fish-Game#1]
Through group discussion, we should come to a consensus on a decided programming language that suits our abilities as well as the platform to build the game :)

**Comment by Shadowsarespooky** [comment]
Using python as the coding language and using pygame as the game engine seems to be the concluded outcome

**Comment by katiepo456** [comment]
I was having issues installing the packages for pygame, if others find a way for proper installation, then please document the instructions. Otherwise, we may have to look into an alternative language+engine.

**Comment by katiepo456** [comment]
Just as a suggestion, Godot Engine is a game engine that can create 2D games in C++. It seems to have its own GUI so it may be more helpful and innovative than trying to program a game in Python. There's also some other good C++ options from this article: https://narrasoft.com/the-top-3-three-c-plus-plus-plusplus-cpp-cplusplus-2d-game-engines-2021/

**Comment by Shadowsarespooky** [comment]
By the time we meet on 2/13/2023 we should know if we want to use Godot and either Python, C++, or its native language GDScript

**Comment by Shadowsarespooky** [comment]
We have chosen Godot and it's native script
